version: '3'

services:
  sound-level-sensor:
    build:
      context: ./sound-level-sensor
      dockerfile: Dockerfile
    container_name: sound-level-sensor
    volumes:
      - soundlevel:/data


  sound-level-monitor:
    build:
      context: ./sound-level-monitor
      dockerfile: Dockerfile
    container_name: sound-level-monitor
    volumes:
      - noisepollution:/data
    depends_on:
      - sound-level-sensor
    environment:
      - LOW_SOUND_LEVEL=40
      - MEDIUM_SOUND_LEVEL=60
      - HIGH_SOUND_LEVEL=80


networks:
  city-noisepollution-network:
    driver: bridge

volumes:
  soundlevel:
  noisepollution:
